<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <AssemblyName>OpenAC.Net.NFSe.Nacional.DANFSe.QuestPDF.Tests</AssemblyName>
    <RootNamespace>OpenAC.Net.NFSe.Nacional.DANFSe.QuestPDF.Tests</RootNamespace>
    <Copyright>Copyright © Projeto OpenAC .Net 2014 - 2025</Copyright>
    <Company>OpenAC .Net - Automação Comercial em .Net</Company>
    <Authors>Projeto OpenAC .Net</Authors>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageId>OpenAC.Net.NFSe.Nacional.DANFSe.QuestPDF.Tests</PackageId>
    <SignAssembly>true</SignAssembly>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <OutputType>Exe</OutputType>
    <Description>Biblioteca de teste para geração e impressão de DANFSe (Documento Auxiliar da NFS-e Nacional) em PDF usando QuestPdf (100% Open Source / MIT).</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit.v3" Version="3.1.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Update="DadosTeste\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenAC.Net.NFSe.Nacional.DANFSe.QuestPDF/OpenAC.Net.NFSe.Nacional.DANFSe.QuestPDF.csproj" />
  </ItemGroup>

</Project>